export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR = 'ERROR';
export const ERRORTOKEN = 'ERRORTOKEN';
export const HIDE_ALERT = 'HIDE_ALERT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const AUTH_USER = 'AUTH_USER';
export const LOG_OUT = 'LOG_OUT';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const SUGGESTIONS = 'SUGGESTIONS';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_USERS = 'GET_USERS';
export const SELECTED_BRANDS = 'SELECTED_BRANDS';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const CLEAN_SUGGESTIONS = 'CLEAN_SUGGESTIONS';
export const FILTER_PRICE = 'FILTER_PRICE';
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS';
export const SELECTED_PAGE = 'SELECTED_PAGE';
export const CLEAN_FILTERS = 'CLEAN_FILTERS';
export const LIST_PRODUCT_ON_TABLE = 'LIST_PRODUCT_ON_TABLE';
export const SIZE_PAGINATION = 'SIZE_PAGINATION';
export const ORDER_TABLE = 'ORDER_TABLE';
export const TABLE_FILTER_BY_CATEGORY = 'TABLE_FILTER_BY_CATEGORY';
export const SORT_TABLE_BY = 'SORT_TABLE_BY';
export const GOTO_TABLE_PAGE = 'GOTO_TABLE_PAGE';
export const GET_USER_TO_EDIT = 'GET_USER_TO_EDIT';
export const GET_PRODUCT_TO_EDIT = 'GET_PRODUCT_TO_EDIT';
export const FETCH_COUNT_OF_BRAND = 'FETCH_COUNT_OF_BRAND';
export const FETCH_COUNT_OF_CATEGORIES = 'FETCH_COUNT_OF_CATEGORIES';
export const FILTER_STOCK = 'FILTER_STOCK';
export const TABLE_FILTER_BRAND = 'TABLE_FILTER_BRAND';
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const PRODUCT_WITH_ORDER = 'PRODUCT_WITH_ORDER';
export const USER_WITH_ORDER = 'USER_WITH_ORDER';
export const TABLE_ORDER_PAGINATION_SIZE = 'TABLE_ORDER_PAGINATION_SIZE';
export const TABLE_USER_ORDER_PAGINATION_SIZE =
	'TABLE_USER_ORDER_PAGINATION_SIZE';
export const FILTER_BY_ORDER_STATUS = 'FILTER_BY_ORDER_STATUS';
export const GET_ALL_DATA_ABOUT_AN_ORDER = 'GET_ALL_DATA_ABOUT_AN_ORDER';
export const CURRENT_PAGE_ORDER_PRODUCT = 'CURRENT_PAGE_ORDER_PRODUCT';
export const CURRENT_PAGE_ORDER_USER = 'CURRENT_PAGE_ORDER_USER';
//carrito
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';

// pago
export const SET_CART = 'SET_CART';
export const GET_PAY = 'GET_PAY';
export const CREATE_CART_USER = 'CREATE_CART_USER';
export const SAVE_ADDRESS_ORDER = 'SAVE_ADDRESS_ORDER';
export const SET_AMMOUNT = 'SET_AMMOUNT';


//deploy
export const SET_MANUAL_AUTHENTICATION = 'SET_MANUAL_AUTHENTICATION';

//user account
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const ADD_DATABASE_FAVORITES = 'ADD_DATABASE_FAVORITES';

// watson assistant
export const INPUT_SUCCESS = 'INPUT_SUCCESS';
export const INPUT_FAIL = 'INPUT_FAIL';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAIL = 'SESSION_FAIL';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_FAIL = 'MESSAGE_FAIL';

//reviews
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const GET_AVERAGE = 'GET_AVERAGE';
export const POST_REVIEW = 'POST_REVIEW';
export const ALL_REVIEWS = 'ALL_REVIEWS';
export const ALL_STARS = 'ALL_STARS';
//cryptos
export const GET_RATES = 'GET_RATES';
