export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR = 'ERROR';
export const HIDE_ALERT = 'HIDE_ALERT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const AUTH_USER = 'AUTH_USER';
export const LOG_OUT = 'LOG_OUT';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const SUGGESTIONS = 'SUGGESTIONS';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_USERS = 'GET_USERS';
export const SELECTED_BRANDS = 'SELECTED_BRANDS';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const CLEAN_SUGGESTIONS = 'CLEAN_SUGGESTIONS';
export const FILTER_PRICE = 'FILTER_PRICE';
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS';
export const SELECTED_PAGE = 'SELECTED_PAGE';
export const CLEAN_FILTERS = 'CLEAN_FILTERS';
export const LIST_PRODUCT_ON_TABLE = 'LIST_PRODUCT_ON_TABLE';
export const SIZE_PAGINATION = 'SIZE_PAGINATION';
export const ORDER_TABLE = 'ORDER_TABLE';
export const TABLE_FILTER_BY_CATEGORY = 'TABLE_FILTER_BY_CATEGORY';
export const SORT_TABLE_BY = 'SORT_TABLE_BY';
export const GOTO_TABLE_PAGE = 'GOTO_TABLE_PAGE';
export const GET_USER_TO_EDIT = 'GET_USER_TO_EDIT';
export const GET_PRODUCT_TO_EDIT = 'GET_PRODUCT_TO_EDIT';


export const TABLE_FILTER_BRAND = 'TABLE_FILTER_BRAND';

//carrito
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';

/////////////////ADMIN
// export const CREATED_BRAND= 'CREATED_BRAND';
